# Setup
title: Steyn de Klerk's Space
title_pt1: Steyn's
title_pt2: Space
tagline: a project and life blog or something
url: https://www.steyn.dk
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# SEO and such

social:
  name: Steyn de Klerk
  links:
    - https://www.linkedin.com/in/steyndk
    - https://github.com/Staindk

# Specify the author for blog posts
author:
  name: Steyn de Klerk
  url: https://www.steyn.dk
  email: me@steyn.dk

# Custom vars
version: 3.0.0

fun_titles:
  - text: Place
    url: /
    css-action: nothin
  - text: Spot
    url: /
    css-action: nothin
  - text: Space
    url: /
    css-action: nothin
  - text: Huis
    url: https://translate.google.com/?sl=af&tl=en&text=huis&op=translate&hl=en
    css-action: highlight-newtab
  - text: Maze
    url: /
    css-action: nothin
  - text: Face
    url: /misc/stainw
    css-action: highlight-sametab
  # - text: Plane
  #   url: /
  #   css-action: nothin
  # - text: Plain
  #   url: /
  #   css-action: nothin
  # - text: Valheim
  #   url: /add/link
  #   css-action: nothin